version: "1"

services:
  mysql:
    image: mysql:8.0.26
    container_name: database-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Unu#2023
    ports:
    - 3309:3306
    - 33061:33060
    networks:
    - td2023 
    
networks:
  td2023:
    name: ms-unu

