version: "1"

services:
  postgres:
    image: postgres:alpine3.14
    container_name: database-postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=Unu#2023
    ports:
    - 5439:5432
    networks:
    - td2023
    
networks:
  td2023:
    name: ms-unu

